name: Java CI with Maven

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 24

    - name: Set DISPLAY for JavaFX (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        echo "DISPLAY=:99" >> $GITHUB_ENV
        nohup xvfb-run --server-args="-screen 0 1920x1080x24" sleep 3600 &
        sleep 3

    - name: Build and test with Maven
      run: mvn -B clean verify